#!/usr/bin/env python3
import os
from threading import Thread

from dotenv import load_dotenv

from chatbots import TelegramBot
from chatbots import VkontakteBot


def _main():
    load_dotenv()

    vkbot = VkontakteBot(os.getenv("VK_TOKEN"))
    tgbot = TelegramBot(os.getenv("TG_TOKEN"))

    Thread(target=vkbot.run).start()
    Thread(target=tgbot.run).start()


if __name__ == '__main__':
    _main()
